version: '2'

services:

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/srv/app
    networks:
      - nodeapp-network
    depends_on: 
      - mongodb
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network
    volumes:
      - ./mongo_data:/data

networks:
  nodeapp-network:
    driver: bridge
